# Generated by Django 5.2.1 on 2025-05-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='avaible_effort',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='selectable_items',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
