# Generated by Django 5.2.1 on 2025-05-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_questionnaire_avaible_effort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireitem',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
