# Generated by Django 5.2.1 on 2025-05-30 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(default=0)),
                ('gender', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('NB', 'No Binary'), ('NL', 'No Listed'), ('U', 'Unknown')], default='U', max_length=2)),
                ('role', models.CharField(choices=[('DEV', 'Developer'), ('UX', 'UX'), ('LEAD', 'Leader')], max_length=4)),
                ('agile_experience', models.CharField(choices=[('NEVER', 'Nunca trabaje con métodos ágiles'), ('OCCASIONAL', 'He trabajado ocasionalmente con métodos ágiles'), ('USUAL', 'Trabajo regularmente con métodos ágiles')], default='NEVER', max_length=10)),
                ('project_type', models.CharField(choices=[('WEB', 'Aplicaciones web'), ('MOBILE', 'Aplicaciones para móviles'), ('OTHER', 'Otra (indicar opción)')], max_length=10)),
                ('project_type_other', models.CharField(blank=True, max_length=100, null=True)),
                ('sprint_planning_experience', models.CharField(choices=[('USUAL', 'Habitualmente participo'), ('SOMETIMES', 'Algunas veces he participado'), ('ONLY_CRITICAL', 'Participo sólo cuando hay ítems críticos relacionados con mi rol'), ('NEVER', 'Nunca participo de esas actividades')], default='NEVER', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireResponseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_items', to='questionnaire.questionnaireitem')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_items', to='responses.questionnaireresponse')),
            ],
        ),
    ]
