# Generated by Django 5.2.1 on 2025-05-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='gender',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('NB', 'No Binary'), ('NL', 'No Listed'), ('U', 'Unknown')], max_length=2),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='sprint_planning_experience',
            field=models.CharField(choices=[('USUAL', 'Habitualmente participo'), ('SOMETIMES', 'Algunas veces he participado'), ('ONLY_CRITICAL', 'Participo sólo cuando hay ítems críticos relacionados con mi rol'), ('NEVER', 'Nunca participo de esas actividades')], max_length=15),
        ),
    ]
