# Generated by Django 5.2.1 on 2025-05-30 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_questionnaire_avaible_effort_and_more'),
        ('responses', '0002_alter_questionnaireresponse_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='questionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_responses', to='questionnaire.questionnaire'),
        ),
    ]
