# Generated by Django 5.2.1 on 2025-06-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0003_questionnaireresponse_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='role_experience',
            field=models.CharField(choices=[('DEV', 'Developer'), ('UX', 'UX'), ('LEAD', 'Leader')], default='<1', max_length=4),
        ),
    ]
