# Generated by Django 5.2.1 on 2025-06-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0006_questionnaireresponse_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'No Binary'), ('NL', 'No Listed'), ('U', 'Unknown')], max_length=2),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='role_experience',
            field=models.CharField(choices=[('<1', 'Junior'), ('1-3', 'Semi Senior'), ('3-5', 'Senior'), ('>5', 'Lead')], default='<1', max_length=4),
        ),
    ]
